### ISSUE TITLE
Ion cannon beams don't stop on hit

### ISSUE THREAD

**Issue by KajiTetsushi** [KajiTetsushi/HomeworldSDL#16]
https://gitlab.com/ThibaultLemaire/HomeworldSDL/-/issues/18

> Effectively giving the impression they pierce through their targets
> ![image](https://user-images.githubusercontent.com/14324391/101244613-7aa5fd80-3742-11eb-85e8-5e79a27ce832.png)

Still happening.

![image](https://user-images.githubusercontent.com/14324391/101244524-023f3c80-3742-11eb-803d-2a4c9a0e953d.png)

**Comment by gondur** [comment]
Hello, yes, can't remember that from vanilla - some suggestion, create a tag ("vanilla bug") separating vanilla bugs from later SDL/porting bugs.

**Comment by KajiTetsushi** [comment]
Yeah, good call @gondur. Let me do that real quick.

Would you hazard a guess that this stems from the SDL lib? I used SDL2 (on macOS) and noticed that the impact effect also looks borked. Wondering if the major version bump broke the API here, too.

Will attach a better screenshot once I'm on my machine.
