### ISSUE TITLE
M09: remove "hunt enemy" line from animatic

### ISSUE THREAD

**Issue by KajiTetsushi** [KajiTetsushi/HomeworldSDL#26]
Homeworld classic: https://youtu.be/n95G0plOrMs
Homeworld remastered: https://youtu.be/cp4lfjCxw_g

This is one of the things the remastered variant did right, in my opinion.

This line feels very on-the-nose:

> It is time to hunt the enemy as they have hunted us.

Removing it should allow the players to fill in the void of what the Kushans are attempting to do.

**Comment by DuendeInexistente** [comment]
Gets into editorializing rather than porting tbh, better have moddability for stuff like that.

**Comment by KajiTetsushi** [comment]
@DuendeInexistente You're right! This should've been left to the modding community but my gut feeling tells me that this stuff is hardcoded to some extent... as are many, many, many things in the source.

For the record, I haven't discovered where this is being referenced yet:
https://github.com/KajiTetsushi/HomeworldSDL/blob/d93dd9230a0403a6e96a250e384249399bfd3176/src/Game/SpeechEvent.h#L845

I'll refine the campaign issues so that we're more interested in exposing as much of the engine as possible than we are about changing even more hardcode. There will be a lot more work to do here if we take that route, but I think that moving forward, that's what anybody wants with the final product.
